// Erfan's Gym Plan v3 — full data (EN/FA)
window.PLAN = {
  meta: {
    title_en: "Erfan's Gym Plan v3",
    title_fa: "برنامه باشگاه ارفان — نسخه ۳",
    goals_en: "Build muscle • Lose fat • Fix lordosis & posture",
    goals_fa: "ساخت عضله • چربی‌سوزی • اصلاح گودی کمر و پاسچر",
  },
  days: {
    1: {
      title_en: "Upper Pull + Posture + Biceps",
      title_fa: "بالاتنه — کشیدنی، پاسچر و جلو بازو",
      tag_en: "PULL",
      tag_fa: "Pull",
      duration: 110,
      warmup: [
        { id: "row-warm", name_en: "Rowing — Progressive Pace", name_fa: "روئینگ — سرعت پلکانی",
          sets: 1, reps_en: "8 min progressive", reps_fa: "۸ دقیقه پلکانی", anim: "row",
          instr_en: "Min 0–2 easy. Min 2–4 moderate. Min 4–6 moderate-hard. Min 6–8 hard pace. Serious cardio that burns fat and prepares posture muscles.",
          instr_fa: "دقیقه ۰–۲ آروم. ۲–۴ متوسط. ۴–۶ متوسط-سخت. ۶–۸ سخت. کاردیوی جدی که هم چربی میسوزونه هم عضلات پاسچر رو آماده میکنه." },
        { id: "band-pa", name_en: "Band Pull‑Apart", name_fa: "باز کردن کش", sets: 1, reps_en: "15", reps_fa: "۱۵", anim: "pullapart",
          instr_en: "Hold band in front at chest height. Pull hands apart until arms are straight. Squeeze shoulder blades. Slow return.",
          instr_fa: "کش رو با دو دست جلوی سینه نگه دار. از طرفین بکش تا دست‌ها صاف بشن. تیغه‌های شونه رو فشار بده. آروم برگردون." },
        { id: "wall-slide", name_en: "Wall Slides", name_fa: "اسلاید روی دیوار", sets: 2, reps_en: "10", reps_fa: "۱۰", anim: "wallslide", youtube: "https://www.youtube.com/shorts/i_0zLUcE-zk",
          instr_en: "Back to wall, feet 15cm out. Press head/back/butt to wall. Arms make 'W', slide up to 'Y' keeping contact.",
          instr_fa: "پشت به دیوار، پاها ۱۵ سانت فاصله. کمر، باسن، پشت سر چسبیده به دیوار. دست‌ها به شکل W. بکش بالا تا شکل Y." },
        { id: "chin-tuck-w", name_en: "Chin Tucks", name_fa: "چونه عقب", sets: 1, reps_en: "10", reps_fa: "۱۰", anim: "chintuck", youtube: "https://www.youtube.com/shorts/3ctIwvT823s",
          instr_en: "Pull head straight back (double chin). Hold 2 sec.",
          instr_fa: "سر رو مستقیم بکش عقب (غبغب درست کن). ۲ ثانیه نگه دار." },
        { id: "high-knees-d1", name_en: "High Knees in Place", name_fa: "زانو بلند درجا", sets: 1, reps_en: "30s", reps_fa: "۳۰ث", anim: "walk", youtube: "https://www.youtube.com/shorts/82pdtHaANGk",
          instr_en: "Run in place bringing knees to hip height. Keep heart rate up.",
          instr_fa: "درجا بدو، زانو رو تا سطح لگن بیار. ضربان قلب بالا." },
        { id: "jumping-jacks-d1", name_en: "Jumping Jacks", name_fa: "جامپینگ جک", sets: 1, reps_en: "30s", reps_fa: "۳۰ث", anim: "generic", youtube: "https://www.youtube.com/shorts/S8V_iXijSwc",
          instr_en: "Jump feet wide as arms go overhead. Continuous.",
          instr_fa: "پاها باز، دست‌ها بالا. پشت سر هم." },
      ],
      main: [
        { id: "lat-pulldown", name_en: "Lat Pulldown", name_fa: "لت پول‌داون", equipment_en: "Lat Pulldown Machine", equipment_fa: "دستگاه لت", sets: 3, reps_en: "10–12", reps_fa: "۱۰–۱۲", anim: "pulldown", youtube: "https://www.instagram.com/reel/DHqsvCuJjUY/?hl=en",
          instr_en: "Sit, lock thigh pad. Overhand grip wider than shoulders. Lean back 10–15°. Pull bar to upper chest by driving elbows DOWN and back. Squeeze shoulder blades. Slow return.",
          instr_fa: "بشین، پد رون رو قفل کن. گرپ Overhand پهن‌تر از شونه. ۱۰–۱۵ درجه عقب. میله رو بکش پایین تا قفسه سینه با کشیدن آرنج به پایین و عقب. تیغه‌های شونه رو فشار بده. آروم بفرست بالا.",
          cue_en: "Drive elbows down to hips — don't pull with hands.",
          cue_fa: "آرنج‌ها رو میکشم پایین به سمت لگن — نه با دست." },
        { id: "cable-row", name_en: "Seated Cable Row", name_fa: "روئینگ کابل نشسته", equipment_en: "Cable Row Machine", equipment_fa: "دستگاه روئینگ کابل", sets: 3, reps_en: "10–12", reps_fa: "۱۰–۱۲", anim: "cablerow", youtube: "https://www.instagram.com/reel/DN0rrNXwrz7/",
          instr_en: "Feet on platform, knees slightly bent. Sit tall. Pull handle to belly button by driving elbows back. Squeeze shoulder blades. Don't rock.",
          instr_fa: "پاها رو پدال، زانو یه کم خم. صاف بشین. دستگیره رو بکش سمت ناف با عقب کشیدن آرنج‌ها. تیغه‌های شونه رو فشار بده. تاب نده." },
        { id: "face-pull", name_en: "Face Pull", name_fa: "فیس پول", equipment_en: "Cable + Rope (face height)", equipment_fa: "کابل + طناب در ارتفاع صورت", sets: 4, reps_en: "15", reps_fa: "۱۵", anim: "facepull", youtube: "https://www.instagram.com/reel/DW7k3vNE455/",
          instr_en: "Light weight! Thumbs back. Pull rope toward face with elbows HIGH — like flexing biceps for a photo. Pause 1 sec.",
          instr_fa: "وزنه سبک! شست‌ها به عقب. طناب رو بکش سمت صورت، آرنج‌های بالا — انگار داری برای عکس بازو نشون میدی. ۱ ثانیه مکث.",
          cue_en: "Gold for fixing rounded shoulders. Don't skip.",
          cue_fa: "طلای شونه‌های جلو افتاده. نزن نشو." },
        { id: "rev-pec", name_en: "Reverse Pec Deck", name_fa: "پک دک معکوس", equipment_en: "Pec Deck (sit backwards)", equipment_fa: "پک دک (برعکس بشین)", sets: 3, reps_en: "12–15", reps_fa: "۱۲–۱۵", anim: "revpec", youtube: "https://www.instagram.com/reel/DUjdugPEyYg/",
          instr_en: "Sit facing the pad. Chest against pad. Pull arms out to the sides — open chest wide. Squeeze rear delts. Slow return.",
          instr_fa: "برعکس بشین — رو به پد. سینه به پد. بازوها رو از طرفین بکش بیرون. پشت شونه‌ها رو محکم فشار بده." },
        { id: "shrug", name_en: "Dumbbell Shrug", name_fa: "شراگ دمبل", equipment_en: "Dumbbells (light)", equipment_fa: "دمبل (سبک)", sets: 3, reps_en: "15", reps_fa: "۱۵", anim: "shrug", youtube: "https://www.youtube.com/shorts/rFsSeClGnNA",
          instr_en: "Shrug shoulders STRAIGHT UP toward ears (don't roll). Tuck chin while shrugging — trains good posture.",
          instr_fa: "شونه‌ها رو مستقیم بفرست بالا سمت گوش (نچرخونشون). همزمان چونه رو ببر عقب — پاسچر خوب رو تمرین میده." },
        { id: "bb-curl", name_en: "Barbell Curl", name_fa: "کرل هالتر", equipment_en: "EZ Bar", equipment_fa: "میله EZ", sets: 3, reps_en: "10", reps_fa: "۱۰", anim: "curl", youtube: "https://www.youtube.com/shorts/PuaJzTatIJM",
          instr_en: "Elbows tucked at sides. Curl up by bending elbows only. Squeeze at top. Lower in 3 seconds.",
          instr_fa: "آرنج‌ها چسبیده به بدن. فقط با خم کردن آرنج بیار بالا. بالا فشار بده. ۳ ثانیه آروم بیار پایین.",
          cue_en: "Don't swing your back. If you swing, weight is too heavy.",
          cue_fa: "با کمرت تاب نده. اگه تاب میدی، وزنه سنگینه." },
        { id: "incline-curl", name_en: "Incline Dumbbell Curl", name_fa: "کرل دمبل شیب‌دار", equipment_en: "Incline Bench 45° + DBs", equipment_fa: "نیمکت ۴۵° + دمبل", sets: 3, reps_en: "10", reps_fa: "۱۰", anim: "inclinecurl", youtube: "https://www.youtube.com/shorts/uCUaRFlA9vE",
          instr_en: "Lie back fully. Arms hang straight, palms forward. Elbows STAY behind body. Curl without moving elbows. Deep stretch at bottom.",
          instr_fa: "کامل تکیه بده عقب. دست‌ها آویزون، کف دست به جلو. آرنج‌ها پشت بدنت بمونن. بدون حرکت دادن آرنج بیار بالا.",
          cue_en: "Targets long head — the bicep peak.",
          cue_fa: "هدف: سر بلند بایسپس — قله بازو." },
        { id: "hammer", name_en: "Hammer Curl", name_fa: "کرل چکشی", equipment_en: "Dumbbells", equipment_fa: "دمبل", sets: 3, reps_en: "12", reps_fa: "۱۲", anim: "hammer", youtube: "https://www.youtube.com/shorts/NyW2fT2gQhM",
          instr_en: "Palms face each other (hammer grip). Curl up to shoulders.",
          instr_fa: "کف دست‌ها رو به هم (مثل چکش). بیار بالا سمت شونه.",
          cue_en: "Targets brachialis — makes arm thicker.",
          cue_fa: "هدف: Brachialis — بازو رو ضخیم‌تر نشون میده." },
        { id: "pallof", name_en: "Pallof Press", name_fa: "پالوف پرس", equipment_en: "Cable (chest height)", equipment_fa: "کابل (ارتفاع سینه)", sets: 3, reps_en: "10 each side", reps_fa: "۱۰ هر طرف", anim: "pallof", youtube: "https://www.facebook.com/61555624303640/videos/pallof-press-tutorial-okay-members-challenge-participants-and-anyone-else-follow/826474749879960/",
          instr_en: "Stand sideways. Push handle straight out. Cable will try to twist you — resist. Hold 2 sec.",
          instr_fa: "کنار دستگاه. مستقیم به جلو هل بده. کابل میخواد بدنت رو بچرخونه — مقاومت کن. ۲ ثانیه نگه دار." },
      ],
      cardio: { id: "row-hiit-d1", name_en: "Rowing HIIT + Incline Walk", name_fa: "روئینگ HIIT + پیاده‌روی شیب‌دار", duration_en: "25 min total", duration_fa: "۲۵ دقیقه مجموع", anim: "row",
        instr_en: "Part 1 (15 min): 10 rounds of 45s hard / 45s easy on rower. Hard = ~28-32 strokes/min, breathing heavy. Easy = recover. Part 2 (10 min): Incline treadmill walk 5–6 km/h, incline 8–10%.",
        instr_fa: "بخش ۱ (۱۵ دقیقه): ۱۰ راند ۴۵ث سخت / ۴۵ث آروم با روئینگ. سخت = ۲۸-۳۲ کشش/دقیقه. آروم = ریکاوری. بخش ۲ (۱۰ دقیقه): تردمیل ۵-۶ کیلومتر/ساعت با شیب ۸-۱۰٪." },
      cooldown: [
        { id: "pec-stretch", name_en: "Doorway Pec Stretch", name_fa: "کشش سینه چهارچوب", reps_en: "60s", reps_fa: "۶۰ث", instr_en: "Forearm on door frame, step forward.", instr_fa: "ساعد رو چهارچوب، یه پا جلو." },
        { id: "trap-stretch", name_en: "Upper Trap Stretch", name_fa: "کشش تراپز بالا", reps_en: "30s each", reps_fa: "۳۰ث هر طرف", instr_en: "Pull head ear-to-shoulder.", instr_fa: "گوش به شونه." },
        { id: "lev-stretch", name_en: "Levator Scapulae Stretch", name_fa: "کشش لواتور اسکاپولا", reps_en: "30s each", reps_fa: "۳۰ث هر طرف", instr_en: "Head 45° toward armpit, then pull.", instr_fa: "سر سمت زیربغل ۴۵°، بعد بکش." },
      ],
    },
    2: {
      title_en: "Lower Body + Core",
      title_fa: "پایین‌تنه و کور",
      tag_en: "LEGS",
      tag_fa: "Legs",
      duration: 105,
      warmup: [
        { id: "bike-warm", name_en: "Stationary Bike — Progressive", name_fa: "دوچرخه ثابت — پلکانی", sets: 1, reps_en: "8 min progressive", reps_fa: "۸ دقیقه پلکانی", anim: "bike",
          instr_en: "Min 0–2 easy spin. Min 2–4 moderate light resistance. Min 4–6 moderate-hard more resistance. Min 6–8 hard, breathing heavy.",
          instr_fa: "دقیقه ۰–۲ آروم. ۲–۴ متوسط، مقاومت کم. ۴–۶ متوسط-سخت، مقاومت بیشتر. ۶–۸ سخت، نفس سنگین." },
        { id: "catcow", name_en: "Cat–Cow Stretch", name_fa: "کشش گربه‌-گاو", sets: 1, reps_en: "10", reps_fa: "۱۰", anim: "catcow", youtube: "https://www.youtube.com/watch?v=vuyUwtHl694",
          instr_en: "Round back up (cat), then dip down looking up (cow). Slow.",
          instr_fa: "کمر رو قوس بده بالا (گربه)، بعد کمر رو بفرست پایین و سر بالا (گاو). آروم." },
        { id: "bw-bridge", name_en: "Bodyweight Glute Bridge", name_fa: "پل گلوت بدون وزنه", sets: 2, reps_en: "15", reps_fa: "۱۵", anim: "bridge", youtube: "https://www.youtube.com/watch?v=ncpMkhXAykg",
          instr_en: "Push hips up by squeezing glutes. Don't arch back.",
          instr_fa: "باسن رو ببر بالا با فشار گلوت. کمر رو قوس نده." },
        { id: "hf-stretch", name_en: "Kneeling Hip Flexor Stretch", name_fa: "کشش فلکسور لگن زانو زده", sets: 1, reps_en: "30s each", reps_fa: "۳۰ث هر طرف", anim: "hipflex", youtube: "https://www.youtube.com/shorts/7lGIfjasuNo",
          instr_en: "Push hips forward. Squeeze glute on the kneeling side.",
          instr_fa: "لگن جلو. گلوت پای عقبی فشار." },
        { id: "bw-squat-d2", name_en: "Bodyweight Squat", name_fa: "اسکات بدون وزنه", sets: 1, reps_en: "15", reps_fa: "۱۵", anim: "squat", youtube: "https://www.youtube.com/watch?v=m0GcZ24pK6k",
          instr_en: "Sit back and down, chest up.",
          instr_fa: "باسن عقب و پایین، سینه بالا." },
        { id: "walk-lunge-d2", name_en: "Walking Lunge", name_fa: "لانج راه رفتنی", sets: 1, reps_en: "10", reps_fa: "۱۰", anim: "splitsquat", youtube: "https://www.youtube.com/watch?v=L8fvypPrzzs",
          instr_en: "Step forward into lunge, then through.",
          instr_fa: "یه قدم برو جلو لانج، بعد رد شو." },
      ],
      main: [
        { id: "goblet", name_en: "Goblet Squat", name_fa: "اسکات گابلت", equipment_en: "Dumbbell", equipment_fa: "دمبل", sets: 3, reps_en: "10–12", reps_fa: "۱۰–۱۲", anim: "squat", youtube: "https://www.youtube.com/shorts/lRYBbchqxtI",
          instr_en: "Hold DB vertical against chest. Sit back and down. Knees track over toes. Push through heels.",
          instr_fa: "دمبل رو عمودی جلوی سینه. مثل نشستن رو صندلی برو پایین. زانوها سمت پنجه. با فشار از پاشنه بلند شو." },
        { id: "rdl", name_en: "Romanian Deadlift (RDL)", name_fa: "ددلیفت رومانیایی (RDL)", equipment_en: "Barbell or DBs", equipment_fa: "هالتر یا دمبل", sets: 3, reps_en: "10–12", reps_fa: "۱۰–۱۲", anim: "rdl", youtube: "https://www.youtube.com/watch?v=7j-2w4-P14I",
          instr_en: "Slight knee bend (locked). Push hips BACK like closing a car door with butt. Lower along legs, back straight.",
          instr_fa: "زانو یه کم خم (قفل). باسن رو بفرست عقب انگار با باسن داری در ماشین رو میبندی. وزنه در امتداد پا، کمر صاف.",
          cue_en: "If back rounds, lower the weight.",
          cue_fa: "اگه کمر خم میشه، وزنه رو سبک کن." },
        { id: "hipthrust", name_en: "Hip Thrust", name_fa: "هیپ تراست", equipment_en: "Bench + Barbell + Pad", equipment_fa: "نیمکت + هالتر + پد", sets: 4, reps_en: "12", reps_fa: "۱۲", anim: "hipthrust", youtube: "https://www.youtube.com/watch?v=3ENrRyaAFEQ",
          instr_en: "Upper back on bench. Drive through heels. Squeeze glutes HARD at top — hold 2 sec. Chin tucked.",
          instr_fa: "بالاتنه روی نیمکت. از پاشنه فشار بده. بالا گلوت‌ها رو محکم فشار بده — ۲ ثانیه. چونه عقب.",
          cue_en: "King of glute exercises — reverses anterior pelvic tilt.",
          cue_fa: "پادشاه تمرین گلوت — گودی کمر رو معکوس میکنه." },
        { id: "legcurl", name_en: "Lying Leg Curl", name_fa: "پشت پا خوابیده", equipment_en: "Leg Curl Machine", equipment_fa: "دستگاه پشت پا", sets: 3, reps_en: "12", reps_fa: "۱۲", anim: "legcurl", youtube: "https://www.youtube.com/shorts/1cnTm01JUhk",
          instr_en: "Pad just above heels. Bend knees to bring heels to butt. Squeeze. Slow 3 sec down.",
          instr_fa: "پد بالای پاشنه. زانو رو خم کن، پاشنه رو بیار سمت باسن. فشار بده. ۳ ثانیه آروم پایین." },
        { id: "deadbug", name_en: "Dead Bug", name_fa: "دد باگ", equipment_en: "Floor mat", equipment_fa: "تشک", sets: 3, reps_en: "10 each side", reps_fa: "۱۰ هر طرف", anim: "deadbug", youtube: "https://www.youtube.com/watch?v=g_BYB0R-4Ws",
          instr_en: "Lower back FLAT against floor. Slowly lower opposite arm + leg. Don't let back arch.",
          instr_fa: "کمر محکم به زمین چسبیده. آروم دست و پای مقابل رو پایین بیار. نذار کمر بلند شه." },
        { id: "birddog", name_en: "Bird Dog", name_fa: "برد داگ", equipment_en: "Floor mat", equipment_fa: "تشک", sets: 3, reps_en: "10 each side", reps_fa: "۱۰ هر طرف", anim: "birddog", youtube: "https://www.youtube.com/watch?v=k2azbhhuKuM",
          instr_en: "Hands under shoulders, knees under hips. Extend opposite arm and leg parallel to floor. 2 sec hold.",
          instr_fa: "دست زیر شونه، زانو زیر باسن. دست و پای مقابل رو موازی زمین صاف کن. ۲ ثانیه نگه دار." },
        { id: "plank", name_en: "Plank", name_fa: "پلانک", equipment_en: "Floor mat", equipment_fa: "تشک", sets: 3, reps_en: "30–45s", reps_fa: "۳۰–۴۵ث", anim: "plank", youtube: "https://www.youtube.com/watch?v=pvIjsG5Svck",
          instr_en: "Forearms + toes on floor. One straight line. Squeeze glutes. Pull belly to spine.",
          instr_fa: "ساعد و انگشت پا روی زمین. یه خط صاف. گلوت‌ها رو فشار بده. ناف رو بکش سمت ستون فقرات." },
      ],
      cardio: { id: "bike-hiit-d2", name_en: "Bike HIIT + Incline Walk", name_fa: "دوچرخه HIIT + پیاده‌روی شیب‌دار", duration_en: "22 min total", duration_fa: "۲۲ دقیقه مجموع", anim: "bike",
        instr_en: "Part 1 (12 min): 8 rounds of 30s sprint / 60s recovery. Sprint = high resistance, max effort. Recovery = easy spin. Part 2 (10 min): Incline walk 5 km/h, incline 10–12%. Don't hold rails.",
        instr_fa: "بخش ۱ (۱۲ دقیقه): ۸ راند ۳۰ث اسپرینت / ۶۰ث ریکاوری. اسپرینت = مقاومت بالا، حداکثر تلاش. ریکاوری = چرخش آروم. بخش ۲ (۱۰ دقیقه): تردمیل ۵ کیلومتر/ساعت با شیب ۱۰-۱۲٪. دستگیره نگیر." },
      cooldown: [
        { id: "couch", name_en: "Couch Stretch", name_fa: "کشش کاوچ", reps_en: "60s each leg", reps_fa: "۶۰ث هر پا", instr_en: "Top of foot on bench, push hips forward.", instr_fa: "روی پا رو نیمکت، لگن جلو." },
        { id: "child", name_en: "Child's Pose", name_fa: "وضعیت کودک", reps_en: "60s", reps_fa: "۶۰ث", instr_en: "Kneel, sit on heels, arms forward.", instr_fa: "زانو، پاشنه، دست جلو." },
      ],
    },
    3: {
      title_en: "Upper Push + Light Legs",
      title_fa: "بالاتنه — هل دادنی و پای سبک",
      tag_en: "PUSH",
      tag_fa: "Push",
      duration: 105,
      warmup: [
        { id: "treadmill-warm", name_en: "Treadmill — Progressive", name_fa: "تردمیل — پلکانی", sets: 1, reps_en: "8 min progressive", reps_fa: "۸ دقیقه پلکانی", anim: "walk",
          instr_en: "Min 0–2 walk 5 km/h no incline. Min 2–4 walk 6 km/h incline 5%. Min 4–6 light jog 8 km/h incline 3%. Min 6–8 jog 9–10 km/h no incline.",
          instr_fa: "دقیقه ۰–۲ پیاده ۵ کیلومتر/ساعت. ۲–۴ پیاده ۶ کیلومتر شیب ۵٪. ۴–۶ ترات سبک ۸ کیلومتر شیب ۳٪. ۶–۸ ترات ۹-۱۰ کیلومتر." },
        { id: "band-pa-2", name_en: "Band Pull‑Apart", name_fa: "باز کردن کش", sets: 1, reps_en: "15", reps_fa: "۱۵", anim: "pullapart",
          instr_en: "Same as Day 1 — pull hands apart, squeeze blades.",
          instr_fa: "مثل روز ۱ — از طرفین بکش، تیغه‌های شونه رو فشار بده." },
        { id: "scap-pushup", name_en: "Scapular Push‑up", name_fa: "شنا اسکاپولار", sets: 2, reps_en: "10", reps_fa: "۱۰", anim: "scappush", youtube: "https://www.youtube.com/shorts/3TsOKiUDzw0",
          instr_en: "Push‑up position, arms straight. Don't bend elbows. Sink chest between blades, then push by spreading blades.",
          instr_fa: "حالت شنا با دست‌های صاف. آرنج رو خم نکن. سینه رو بفرست بین تیغه‌های شونه، بعد با باز کردن تیغه‌ها فشار بده بالا." },
        { id: "chin-tuck-w3", name_en: "Chin Tucks", name_fa: "چونه عقب", sets: 1, reps_en: "10", reps_fa: "۱۰", anim: "chintuck",
          instr_en: "Pull head straight back.",
          instr_fa: "سر رو مستقیم بکش عقب." },
        { id: "arm-circles-d3", name_en: "Arm Circles", name_fa: "دایره دست", sets: 1, reps_en: "30s", reps_fa: "۳۰ث", anim: "generic", youtube: "https://www.youtube.com/watch?v=140RTNMciH8",
          instr_en: "Big circles forward 15s, backward 15s.",
          instr_fa: "دایره بزرگ ۱۵ث جلو، ۱۵ث عقب." },
        { id: "pushup-downdog-d3", name_en: "Push‑up to Down Dog", name_fa: "شنا به سگ سرپایین", sets: 1, reps_en: "10", reps_fa: "۱۰", anim: "scappush", youtube: "https://www.youtube.com/watch?v=zlzmTx_l2Bk",
          instr_en: "Push-up, then push hips up high to down dog. Repeat.",
          instr_fa: "شنا، بعد باسن رو بفرست بالا به سگ سرپایین. تکرار." },
      ],
      main: [
        { id: "incline-press", name_en: "Incline Dumbbell Press", name_fa: "پرس دمبل بالاسینه", equipment_en: "Incline Bench 30–45° + DBs", equipment_fa: "نیمکت ۳۰–۴۵° + دمبل", sets: 3, reps_en: "10", reps_fa: "۱۰", anim: "inclinepress", youtube: "https://www.youtube.com/shorts/8fXfwG4ftaQ",
          instr_en: "DBs at chest level beside shoulders. Press up and slightly together. Don't lock elbows. Slow 3 sec down.",
          instr_fa: "دمبل‌ها کنار شونه در سطح سینه. بفرست بالا و یه کم به سمت هم. آرنج قفل نه. ۳ ثانیه آروم پایین." },
        { id: "shoulder-press", name_en: "Seated Machine Shoulder Press", name_fa: "پرس سرشانه دستگاه", equipment_en: "Shoulder Press Machine", equipment_fa: "دستگاه پرس سرشانه", sets: 3, reps_en: "10–12", reps_fa: "۱۰–۱۲", anim: "shoulderpress", youtube: "https://www.youtube.com/watch?v=WvLMauqrnK8",
          instr_en: "Back firmly against pad — critical for lordosis. Don't arch lower back. Ribs down.",
          instr_fa: "پشت رو محکم به پد بچسبون — برای گودی کمرت حیاتیه. کمر رو قوس نده. دنده‌ها پایین.",
          cue_en: "Can't avoid arching? Reduce range of motion.",
          cue_fa: "نمیتونی بدون قوس بزنی؟ دامنه حرکت رو کم کن." },
        { id: "lateral", name_en: "Lateral Raise", name_fa: "نشر جانب", equipment_en: "Dumbbells (LIGHT, 4–5kg)", equipment_fa: "دمبل سبک (۴–۵ کیلو)", sets: 3, reps_en: "12–15", reps_fa: "۱۲–۱۵", anim: "lateral", youtube: "https://www.youtube.com/shorts/xyK8UiC-BUw",
          instr_en: "Slight elbow bend. Lead with elbows. Don't go above parallel. No swinging.",
          instr_fa: "آرنج یه کم خم. با آرنج هدایت کن. از موازی بالاتر نرو. تاب نده." },
        { id: "tri-pushdown", name_en: "Tricep Pushdown", name_fa: "پشت بازو سیم‌کش", equipment_en: "Cable + Rope/Bar", equipment_fa: "کابل + طناب/میله", sets: 3, reps_en: "12", reps_fa: "۱۲", anim: "triceps", youtube: "https://www.youtube.com/shorts/Rc7-euA8FDI",
          instr_en: "Elbows tucked at sides — DON'T move them. Only forearms move. Separate rope at bottom.",
          instr_fa: "آرنج چسبیده به بدن — تکون نمیخوره. فقط ساعد حرکت میکنه. پایین، سر طناب‌ها رو از هم باز کن." },
        { id: "split-squat", name_en: "Bulgarian Split Squat", name_fa: "اسپلیت اسکات بلغاری", equipment_en: "Bench + Dumbbells", equipment_fa: "نیمکت + دمبل", sets: 3, reps_en: "10 each leg", reps_fa: "۱۰ هر پا", anim: "splitsquat", youtube: "https://www.youtube.com/shorts/SwG1rVGUgRQ",
          instr_en: "60–80cm in front of bench. Top of foot on bench. Most weight on FRONT leg. Push through front heel.",
          instr_fa: "۶۰–۸۰ سانت جلوی نیمکت. روی پای یه پا رو نیمکت. بیشتر وزن روی پای جلو." },
        { id: "calf-raise", name_en: "Standing Calf Raise", name_fa: "ساق پا ایستاده", equipment_en: "Calf Raise Machine", equipment_fa: "دستگاه ساق پا", sets: 3, reps_en: "15", reps_fa: "۱۵", anim: "calf", youtube: "https://www.youtube.com/shorts/rsOLKY02m70",
          instr_en: "Balls of feet on platform, heels off. Up high (1 sec hold), slow down. Full range.",
          instr_fa: "نوک پا رو پدال، پاشنه آویزون. تا میتونی بلند شو (۱ ثانیه بالا)، آروم پایین. دامنه کامل." },
        { id: "side-plank", name_en: "Side Plank", name_fa: "پلانک جانبی", equipment_en: "Floor mat", equipment_fa: "تشک", sets: 3, reps_en: "25–30s each", reps_fa: "۲۵–۳۰ث هر طرف", anim: "sideplank", youtube: "https://www.youtube.com/shorts/sJwYvq2UiQ4",
          instr_en: "Elbow under shoulder. Hips up — one straight line. Don't sag.",
          instr_fa: "آرنج زیر شونه. باسن بالا — یه خط صاف. نذار بیفته." },
      ],
      cardio: { id: "treadmill-hiit-d3", name_en: "Treadmill HIIT + Incline Walk", name_fa: "تردمیل HIIT + پیاده‌روی شیب‌دار", duration_en: "25 min total", duration_fa: "۲۵ دقیقه مجموع", anim: "walk",
        instr_en: "Part 1 (15 min): 10 rounds of 45s run / 45s walk. Run 12–14 km/h, walk 5–6 km/h. This matches football conditioning. Part 2 (10 min): Incline walk 5–6 km/h, incline 8–10%.",
        instr_fa: "بخش ۱ (۱۵ دقیقه): ۱۰ راند ۴۵ث دویدن / ۴۵ث پیاده‌روی. دویدن ۱۲-۱۴ کیلومتر، پیاده ۵-۶ کیلومتر. این مثل تمرین فوتباله. بخش ۲ (۱۰ دقیقه): شیب ۸-۱۰٪، ۵-۶ کیلومتر/ساعت." },
      cooldown: [
        { id: "pec-stretch-2", name_en: "Doorway Pec Stretch", name_fa: "کشش سینه چهارچوب", reps_en: "60s", reps_fa: "۶۰ث", instr_en: "Forearm on door frame, step forward.", instr_fa: "ساعد رو چهارچوب، یه پا جلو." },
        { id: "hf-stretch-2", name_en: "Kneeling Hip Flexor Stretch", name_fa: "کشش فلکسور لگن", reps_en: "60s each leg", reps_fa: "۶۰ث هر پا", instr_en: "Push hips forward, squeeze rear glute.", instr_fa: "لگن جلو، گلوت پای عقبی فشار." },
        { id: "subocc", name_en: "Suboccipital Release", name_fa: "آزاد‌سازی پس‌سری", reps_en: "60s", reps_fa: "۶۰ث", instr_en: "Tennis ball under base of skull, relax.", instr_fa: "توپ تنیس زیر استخوون پس سر." },
      ],
    },
    4: {
      title_en: "Agility + Cardio + Football Fitness",
      title_fa: "چابکی، کاردیو و آمادگی فوتبال",
      tag_en: "AGILITY",
      tag_fa: "Agility",
      duration: 65,
      warmup: [
        { id: "easy-jog", name_en: "Easy Treadmill Jog", name_fa: "ترات سبک تردمیل", sets: 1, reps_en: "3 min @ 7–8 km/h", reps_fa: "۳ دقیقه با ۷–۸ کیلومتر/ساعت", anim: "walk",
          instr_en: "Just to raise body temperature.", instr_fa: "فقط برای بالا بردن دمای بدن." },
        { id: "leg-swing-fb", name_en: "Leg Swings (Front–Back)", name_fa: "تاب پا (جلو-عقب)", sets: 1, reps_en: "10 each leg", reps_fa: "۱۰ هر پا", anim: "generic",
          instr_en: "Hold a wall. Swing one leg forward and back like a pendulum.",
          instr_fa: "دیوار رو بگیر. یه پا رو مثل آونگ جلو-عقب تاب بده." },
        { id: "leg-swing-side", name_en: "Leg Swings (Side to Side)", name_fa: "تاب پا (پهلو به پهلو)", sets: 1, reps_en: "10 each leg", reps_fa: "۱۰ هر پا", anim: "generic",
          instr_en: "Same but swinging across body and out.",
          instr_fa: "همون ولی از روی بدن به بیرون." },
        { id: "hip-circles", name_en: "Hip Circles", name_fa: "دایره لگن", sets: 1, reps_en: "10 each direction", reps_fa: "۱۰ هر جهت", anim: "generic",
          instr_en: "Lift knee up, draw circles with knee.",
          instr_fa: "زانو رو بالا بیار، با زانو دایره بکش." },
        { id: "walk-lunge-twist", name_en: "Walking Lunges with Twist", name_fa: "لانج راه رفتنی با چرخش", sets: 1, reps_en: "10 total", reps_fa: "۱۰ مجموع", anim: "splitsquat",
          instr_en: "Step forward into lunge, rotate torso toward front leg. Step through.",
          instr_fa: "یه قدم برو جلو لانج، بالاتنه رو بچرخون سمت پای جلو. رد شو." },
        { id: "high-knees", name_en: "High Knees in Place", name_fa: "زانو بلند درجا", sets: 1, reps_en: "30s", reps_fa: "۳۰ث", anim: "walk",
          instr_en: "Run in place bringing knees to hip height.",
          instr_fa: "درجا بدو، زانو رو تا سطح لگن بیار بالا." },
        { id: "butt-kicks", name_en: "Butt Kicks", name_fa: "ضربه به باسن", sets: 1, reps_en: "30s", reps_fa: "۳۰ث", anim: "walk",
          instr_en: "Run in place kicking heels to butt.",
          instr_fa: "درجا بدو، پاشنه رو سمت باسن بکوب." },
      ],
      main: [
        { id: "lat-shuffle", name_en: "Lateral Shuffles", name_fa: "شافل جانبی", equipment_en: "2 cones, 5m apart", equipment_fa: "۲ مخروط با فاصله ۵ متر", sets: 4, reps_en: "20s each", reps_fa: "۲۰ث هر ست", anim: "generic",
          instr_en: "Athletic stance (knees bent, low). Shuffle sideways cone to cone, staying low. Don't cross feet — quick small steps. Touch ground at each cone.",
          instr_fa: "حالت ورزشی (زانو خم، کوتاه). از یه مخروط به اون یکی به پهلو حرکت کن، کوتاه بمون. پاها رو تو هم نذار — قدم‌های ریز و سریع. پای هر مخروط زمین رو لمس کن.",
          cue_en: "Football: defensive positioning, side-to-side movement.",
          cue_fa: "فوتبال: پوزیشن دفاعی، حرکت جانبی." },
        { id: "t-drill", name_en: "T-Drill", name_fa: "تمرین T", equipment_en: "4 cones in T shape", equipment_fa: "۴ مخروط به شکل T", sets: 4, reps_en: "1 rep / 30s rest", reps_fa: "۱ تکرار / ۳۰ث استراحت", anim: "generic",
          instr_en: "Sprint 5m forward to top of T → shuffle left 3m → shuffle right 6m → shuffle back 3m → backpedal 5m to start.",
          instr_fa: "اسپرینت ۵ متر جلو تا بالای T ← شافل چپ ۳ متر ← شافل راست ۶ متر ← شافل برگشت ۳ متر ← بک‌پدال ۵ متر تا شروع.",
          cue_en: "Football: multi-direction change, real game movement.",
          cue_fa: "فوتبال: تغییر جهت چند جانبه، حرکت واقعی بازی." },
        { id: "shuttle-run", name_en: "Shuttle Run (5-10-5)", name_fa: "شاتل ران ۵-۱۰-۵", equipment_en: "3 cones, 5m apart", equipment_fa: "۳ مخروط با فاصله ۵ متر", sets: 4, reps_en: "1 rep / 45s rest", reps_fa: "۱ تکرار / ۴۵ث استراحت", anim: "generic",
          instr_en: "Start at middle. Sprint 5m right, touch ground. Sprint 10m left, touch. Sprint 5m back to middle.",
          instr_fa: "شروع از وسط. اسپرینت ۵ متر راست، زمین رو لمس کن. اسپرینت ۱۰ متر چپ، لمس. اسپرینت ۵ متر برگرد به وسط.",
          cue_en: "Football: acceleration, deceleration, change of direction.",
          cue_fa: "فوتبال: شتاب، ترمز، تغییر جهت." },
        { id: "carioca", name_en: "Carioca (Grapevine)", name_fa: "کاریوکا", equipment_en: "Open space", equipment_fa: "فضای باز", sets: 3, reps_en: "15m each direction", reps_fa: "۱۵ متر هر جهت", anim: "generic",
          instr_en: "Move sideways, crossing trailing leg in front of, then behind, your lead leg alternately.",
          instr_fa: "به پهلو حرکت کن، پای عقبی رو یک بار از جلو، یک بار از پشت پای جلویی رد کن.",
          cue_en: "Football: hip mobility for kicking, side movement.",
          cue_fa: "فوتبال: تحرک لگن برای شوت، حرکت جانبی." },
        { id: "box-jump", name_en: "Box Jumps (or Squat Jumps)", name_fa: "باکس جامپ (یا اسکات جامپ)", equipment_en: "Sturdy box / bench", equipment_fa: "جعبه محکم یا نیمکت", sets: 3, reps_en: "6", reps_fa: "۶", anim: "squat",
          instr_en: "Squat slightly, swing arms back, explode UP onto box. Step down (don't jump down).",
          instr_fa: "کمی اسکات، دست‌ها عقب، انفجاری بپر بالا روی جعبه. پایین رو پیاده شو.",
          cue_en: "Football: vertical jump for headers, explosive starts.",
          cue_fa: "فوتبال: پرش عمودی برای هد، شروع انفجاری." },
        { id: "broad-jump", name_en: "Broad Jumps", name_fa: "پرش طول", equipment_en: "Open space", equipment_fa: "فضای باز", sets: 3, reps_en: "5", reps_fa: "۵", anim: "squat",
          instr_en: "Feet shoulder-width. Swing arms back, bend knees. Jump as far forward as you can. Land soft, balanced.",
          instr_fa: "پاها به اندازه شونه. دست‌ها عقب، زانو خم. تا میتونی به جلو بپر. نرم و با تعادل فرود بیا.",
          cue_en: "Football: horizontal explosive power for sprints.",
          cue_fa: "فوتبال: قدرت انفجاری افقی برای اسپرینت." },
        { id: "lat-bound", name_en: "Lateral Bounds", name_fa: "پرش جانبی", equipment_en: "Open space", equipment_fa: "فضای باز", sets: 3, reps_en: "6 each side", reps_fa: "۶ هر طرف", anim: "generic",
          instr_en: "Stand on one leg. Jump sideways onto the other. Stick the landing 1 sec.",
          instr_fa: "رو یه پا وایسا. به پهلو بپر روی پای دیگه. ۱ ثانیه فرود رو نگه دار.",
          cue_en: "Football: lateral push-off power for cuts and dodges.",
          cue_fa: "فوتبال: قدرت رانش جانبی برای دریبل و فرار." },
        { id: "skater-jump", name_en: "Skater Jumps", name_fa: "پرش اسکیتر", equipment_en: "Open space", equipment_fa: "فضای باز", sets: 3, reps_en: "10 (5 each side)", reps_fa: "۱۰ (۵ هر طرف)", anim: "generic",
          instr_en: "Same as lateral bounds but faster, continuous.",
          instr_fa: "مثل lateral bounds ولی سریع‌تر، پشت سر هم." },
        { id: "goblet-light", name_en: "Goblet Squat (light)", name_fa: "اسکات گابلت (سبک)", equipment_en: "Dumbbell", equipment_fa: "دمبل", sets: 3, reps_en: "10", reps_fa: "۱۰", anim: "squat",
          instr_en: "Use a weight you could do 15 reps with — but only do 10. Focus on speed UP.",
          instr_fa: "وزنه‌ای بزن که میتونی ۱۵ تکرار باهاش بزنی — ولی فقط ۱۰. روی سرعت بالا اومدن تمرکز کن." },
        { id: "wood-chop", name_en: "Cable Wood Chop", name_fa: "وود چاپ کابل", equipment_en: "Cable, handle high", equipment_fa: "کابل، دستگیره بالا", sets: 3, reps_en: "10 each side", reps_fa: "۱۰ هر طرف", anim: "pallof",
          instr_en: "Stand sideways. Both hands on handle, arms straight. Pull diagonally across body to opposite hip — rotate through core. Slow return.",
          instr_fa: "به پهلو وایسا. دو دست روی دستگیره، دست‌ها صاف. مورب از روی بدن به سمت لگن مقابل بکش — با چرخش کور. آروم برگردون.",
          cue_en: "Football: rotational power for kicking and shooting.",
          cue_fa: "فوتبال: قدرت چرخشی برای شوت و پاس." },
      ],
      cardio: { id: "treadmill-hiit", name_en: "Treadmill HIIT — 30s sprint / 30s walk", name_fa: "تردمیل HIIT — ۳۰ث اسپرینت / ۳۰ث پیاده", duration_en: "12 rounds + 3 min cooldown", duration_fa: "۱۲ راند + ۳ دقیقه سرد کردن", anim: "walk",
        instr_en: "Sprint 12–14 km/h. Walk 5–6 km/h. Football is exactly this pattern — sprint, jog, walk, sprint.",
        instr_fa: "اسپرینت ۱۲–۱۴ کیلومتر/ساعت. پیاده‌روی ۵–۶ کیلومتر/ساعت. فوتبال دقیقا همین الگوئه — اسپرینت، ترات، پیاده، اسپرینت." },
      cooldown: [
        { id: "treadmill-walk", name_en: "Walk on Treadmill", name_fa: "پیاده‌روی تردمیل", reps_en: "2–3 min", reps_fa: "۲–۳ دقیقه", instr_en: "Easy pace.", instr_fa: "سرعت آروم." },
        { id: "quad-stretch", name_en: "Standing Quad Stretch", name_fa: "کشش چهارسر ایستاده", reps_en: "30s each leg", reps_fa: "۳۰ث هر پا", instr_en: "Pull foot to butt.", instr_fa: "پا رو بکش به سمت باسن." },
        { id: "ham-stretch", name_en: "Standing Hamstring Stretch", name_fa: "کشش پشت ران ایستاده", reps_en: "30s each leg", reps_fa: "۳۰ث هر پا", instr_en: "Heel on bench, lean forward.", instr_fa: "پاشنه رو نیمکت، خم شو جلو." },
        { id: "calf-stretch", name_en: "Standing Calf Stretch", name_fa: "کشش ساق ایستاده", reps_en: "30s each leg", reps_fa: "۳۰ث هر پا", instr_en: "Wall, one leg back, heel down.", instr_fa: "دیوار، یه پا عقب، پاشنه پایین." },
        { id: "hf-stretch-d4", name_en: "Kneeling Hip Flexor", name_fa: "کشش فلکسور لگن زانو زده", reps_en: "60s each leg", reps_fa: "۶۰ث هر پا", instr_en: "Push hips forward, squeeze rear glute.", instr_fa: "لگن جلو، گلوت پای عقبی فشار." },
        { id: "child-d4", name_en: "Child's Pose", name_fa: "وضعیت کودک", reps_en: "60s", reps_fa: "۶۰ث", instr_en: "Kneel, sit on heels, arms forward.", instr_fa: "زانو، پاشنه، دست جلو." },
      ],
    },
  },
  expectations_4_6: {
    en: ["Better posture (less back arch, shoulders back)", "Stronger weights on every exercise", "2–4 kg fat loss with decent diet", "Visible bicep development beginning", "Better energy and sleep"],
    fa: ["پاسچر بهتر (قوس کمر کمتر، شونه‌ها عقب‌تر)", "وزنه‌های قوی‌تر تو هر حرکت", "۲–۴ کیلو کاهش چربی (با غذای درست)", "شروع رشد قابل دیدن جلو بازو", "انرژی و خواب بهتر"],
  },
  expectations_3_6: {
    en: "Visible muscle, much better posture, significantly leaner, biceps notably bigger.",
    fa: "عضله واضح، پاسچر خیلی بهتر، خیلی لاغرتر، جلو بازوی خیلی بزرگ‌تر.",
  },
  habits: [
    { en: "Chin Tucks — 10 reps every hour at desk.", fa: "هر ساعت ۱۰ تا چونه عقب پشت میز." },
    { en: "Hip Flexor Stretch — 60s each leg, morning + night.", fa: "کشش فلکسور لگن — هر پا ۶۰ ثانیه، صبح و شب." },
    { en: "Glute Bridge — 15 reps when you wake up.", fa: "پل گلوتی — صبح که بیدار شدی ۱۵ تا." },
    { en: "Stand up every 45 min at your desk.", fa: "هر ۴۵ دقیقه از پشت میز پاشو." },
    { en: "Walk 8,000–10,000 steps per day.", fa: "روزی ۸ تا ۱۰ هزار قدم." },
  ],
};
